from itertools import takewhile
UylkJmTOgKHNvMwptSIsnhDxCALErPWcVFQ=float
UylkJmTOgKHNvMwptSIsnhDxCALErPWcVFo=int
UylkJmTOgKHNvMwptSIsnhDxCALErPWcVFd=True
UylkJmTOgKHNvMwptSIsnhDxCALErPWcVFi=len
UylkJmTOgKHNvMwptSIsnhDxCALErPWcVFb=range
UylkJmTOgKHNvMwptSIsnhDxCALErPWcVXG=enumerate
UylkJmTOgKHNvMwptSIsnhDxCALErPWcVXF=max
UylkJmTOgKHNvMwptSIsnhDxCALErPWcVXf=min
UylkJmTOgKHNvMwptSIsnhDxCALErPWcVXY=list
from typing import List,NamedTuple,Union
from p2.src.algorithm_api import Algorithm
from p2.src.data_api import Instance,Solution,Schedule,Task
UylkJmTOgKHNvMwptSIsnhDxCALErPWcVGj=1
UylkJmTOgKHNvMwptSIsnhDxCALErPWcVGq=0
class MachineState(NamedTuple):
 UylkJmTOgKHNvMwptSIsnhDxCALErPWcVGR:UylkJmTOgKHNvMwptSIsnhDxCALErPWcVFQ
 UylkJmTOgKHNvMwptSIsnhDxCALErPWcVGb:UylkJmTOgKHNvMwptSIsnhDxCALErPWcVFQ
 index:UylkJmTOgKHNvMwptSIsnhDxCALErPWcVFo
def UylkJmTOgKHNvMwptSIsnhDxCALErPWcVGF(UylkJmTOgKHNvMwptSIsnhDxCALErPWcVGd):
 return UylkJmTOgKHNvMwptSIsnhDxCALErPWcVGd.speed
def UylkJmTOgKHNvMwptSIsnhDxCALErPWcVGX(UylkJmTOgKHNvMwptSIsnhDxCALErPWcVFa):
 return UylkJmTOgKHNvMwptSIsnhDxCALErPWcVFa[UylkJmTOgKHNvMwptSIsnhDxCALErPWcVGj].duration
def UylkJmTOgKHNvMwptSIsnhDxCALErPWcVGf(UylkJmTOgKHNvMwptSIsnhDxCALErPWcVFa:Task):
 return UylkJmTOgKHNvMwptSIsnhDxCALErPWcVFa.ready
def UylkJmTOgKHNvMwptSIsnhDxCALErPWcVGY(UylkJmTOgKHNvMwptSIsnhDxCALErPWcVGz,UylkJmTOgKHNvMwptSIsnhDxCALErPWcVGo,UylkJmTOgKHNvMwptSIsnhDxCALErPWcVFf,UylkJmTOgKHNvMwptSIsnhDxCALErPWcVFG,UylkJmTOgKHNvMwptSIsnhDxCALErPWcVFY,enumerated):
 UylkJmTOgKHNvMwptSIsnhDxCALErPWcVGz.sort(key=UylkJmTOgKHNvMwptSIsnhDxCALErPWcVGF)
 UylkJmTOgKHNvMwptSIsnhDxCALErPWcVGo.sort(key=UylkJmTOgKHNvMwptSIsnhDxCALErPWcVGX,reverse=UylkJmTOgKHNvMwptSIsnhDxCALErPWcVFd)
 for UylkJmTOgKHNvMwptSIsnhDxCALErPWcVGd in UylkJmTOgKHNvMwptSIsnhDxCALErPWcVGz:
  if UylkJmTOgKHNvMwptSIsnhDxCALErPWcVFi(UylkJmTOgKHNvMwptSIsnhDxCALErPWcVGo)>0:
   UylkJmTOgKHNvMwptSIsnhDxCALErPWcVGi=UylkJmTOgKHNvMwptSIsnhDxCALErPWcVGo.pop(0)
   UylkJmTOgKHNvMwptSIsnhDxCALErPWcVGb=UylkJmTOgKHNvMwptSIsnhDxCALErPWcVGi[UylkJmTOgKHNvMwptSIsnhDxCALErPWcVGj].ready+UylkJmTOgKHNvMwptSIsnhDxCALErPWcVGi[UylkJmTOgKHNvMwptSIsnhDxCALErPWcVGj].duration*UylkJmTOgKHNvMwptSIsnhDxCALErPWcVGd.speed
   UylkJmTOgKHNvMwptSIsnhDxCALErPWcVFf.append(UylkJmTOgKHNvMwptSIsnhDxCALErPWcVGi[0])
   UylkJmTOgKHNvMwptSIsnhDxCALErPWcVFG[UylkJmTOgKHNvMwptSIsnhDxCALErPWcVGd.index]=UylkJmTOgKHNvMwptSIsnhDxCALErPWcVFG[UylkJmTOgKHNvMwptSIsnhDxCALErPWcVGd.index]._replace(task_end_time=UylkJmTOgKHNvMwptSIsnhDxCALErPWcVGb)
   UylkJmTOgKHNvMwptSIsnhDxCALErPWcVFY[UylkJmTOgKHNvMwptSIsnhDxCALErPWcVGd.index].append(UylkJmTOgKHNvMwptSIsnhDxCALErPWcVGi[0])
   enumerated.remove(UylkJmTOgKHNvMwptSIsnhDxCALErPWcVGi)
class Algorithm136705(Algorithm):
 def UylkJmTOgKHNvMwptSIsnhDxCALErPWcVGu(self,UylkJmTOgKHNvMwptSIsnhDxCALErPWcVFz:Instance)->Solution:
  UylkJmTOgKHNvMwptSIsnhDxCALErPWcVFX:UylkJmTOgKHNvMwptSIsnhDxCALErPWcVFQ=0
  UylkJmTOgKHNvMwptSIsnhDxCALErPWcVFf=[]
  UylkJmTOgKHNvMwptSIsnhDxCALErPWcVFY=[[]for i in UylkJmTOgKHNvMwptSIsnhDxCALErPWcVFb(UylkJmTOgKHNvMwptSIsnhDxCALErPWcVFz.no_machines)]
  UylkJmTOgKHNvMwptSIsnhDxCALErPWcVFG=[MachineState(UylkJmTOgKHNvMwptSIsnhDxCALErPWcVGR,0,i)for i,UylkJmTOgKHNvMwptSIsnhDxCALErPWcVGR in UylkJmTOgKHNvMwptSIsnhDxCALErPWcVXG(UylkJmTOgKHNvMwptSIsnhDxCALErPWcVFz.machine_speeds)]
  UylkJmTOgKHNvMwptSIsnhDxCALErPWcVFu=UylkJmTOgKHNvMwptSIsnhDxCALErPWcVFz.tasks
  UylkJmTOgKHNvMwptSIsnhDxCALErPWcVFu.sort(key=UylkJmTOgKHNvMwptSIsnhDxCALErPWcVGf)
  UylkJmTOgKHNvMwptSIsnhDxCALErPWcVFB=[[i,val]for i,val in UylkJmTOgKHNvMwptSIsnhDxCALErPWcVXG(UylkJmTOgKHNvMwptSIsnhDxCALErPWcVFu,start=1)]
  while UylkJmTOgKHNvMwptSIsnhDxCALErPWcVFi(UylkJmTOgKHNvMwptSIsnhDxCALErPWcVFf)<UylkJmTOgKHNvMwptSIsnhDxCALErPWcVFz.no_tasks:
   UylkJmTOgKHNvMwptSIsnhDxCALErPWcVGz=UylkJmTOgKHNvMwptSIsnhDxCALErPWcVGe(UylkJmTOgKHNvMwptSIsnhDxCALErPWcVFG,UylkJmTOgKHNvMwptSIsnhDxCALErPWcVFX)
   UylkJmTOgKHNvMwptSIsnhDxCALErPWcVGo=UylkJmTOgKHNvMwptSIsnhDxCALErPWcVGB(UylkJmTOgKHNvMwptSIsnhDxCALErPWcVFB,UylkJmTOgKHNvMwptSIsnhDxCALErPWcVFX)
   if UylkJmTOgKHNvMwptSIsnhDxCALErPWcVFi(UylkJmTOgKHNvMwptSIsnhDxCALErPWcVGz)and UylkJmTOgKHNvMwptSIsnhDxCALErPWcVFi(UylkJmTOgKHNvMwptSIsnhDxCALErPWcVGo)>0:
    UylkJmTOgKHNvMwptSIsnhDxCALErPWcVGY(UylkJmTOgKHNvMwptSIsnhDxCALErPWcVGz,UylkJmTOgKHNvMwptSIsnhDxCALErPWcVGo,UylkJmTOgKHNvMwptSIsnhDxCALErPWcVFf,UylkJmTOgKHNvMwptSIsnhDxCALErPWcVFG,UylkJmTOgKHNvMwptSIsnhDxCALErPWcVFY,UylkJmTOgKHNvMwptSIsnhDxCALErPWcVFB)
    UylkJmTOgKHNvMwptSIsnhDxCALErPWcVFX+=1
   elif UylkJmTOgKHNvMwptSIsnhDxCALErPWcVFi(UylkJmTOgKHNvMwptSIsnhDxCALErPWcVGz)==0:
    UylkJmTOgKHNvMwptSIsnhDxCALErPWcVFX=UylkJmTOgKHNvMwptSIsnhDxCALErPWcVXF(UylkJmTOgKHNvMwptSIsnhDxCALErPWcVXf(UylkJmTOgKHNvMwptSIsnhDxCALErPWcVFG,key=lambda UylkJmTOgKHNvMwptSIsnhDxCALErPWcVGd:UylkJmTOgKHNvMwptSIsnhDxCALErPWcVGd.task_end_time).task_end_time,UylkJmTOgKHNvMwptSIsnhDxCALErPWcVFX)
   else:
    UylkJmTOgKHNvMwptSIsnhDxCALErPWcVFX+=1
  return UylkJmTOgKHNvMwptSIsnhDxCALErPWcVGa(UylkJmTOgKHNvMwptSIsnhDxCALErPWcVFz,UylkJmTOgKHNvMwptSIsnhDxCALErPWcVFY)
def UylkJmTOgKHNvMwptSIsnhDxCALErPWcVGB(UylkJmTOgKHNvMwptSIsnhDxCALErPWcVFu,UylkJmTOgKHNvMwptSIsnhDxCALErPWcVFX:UylkJmTOgKHNvMwptSIsnhDxCALErPWcVFo):
 return UylkJmTOgKHNvMwptSIsnhDxCALErPWcVXY(UylkJmTOgKHNvMwptSIsnhDxCALErPWcVFe(lambda UylkJmTOgKHNvMwptSIsnhDxCALErPWcVFa:UylkJmTOgKHNvMwptSIsnhDxCALErPWcVFa[UylkJmTOgKHNvMwptSIsnhDxCALErPWcVGj].ready<=UylkJmTOgKHNvMwptSIsnhDxCALErPWcVFX,UylkJmTOgKHNvMwptSIsnhDxCALErPWcVFu))
def UylkJmTOgKHNvMwptSIsnhDxCALErPWcVGe(UylkJmTOgKHNvMwptSIsnhDxCALErPWcVFG,UylkJmTOgKHNvMwptSIsnhDxCALErPWcVFX:UylkJmTOgKHNvMwptSIsnhDxCALErPWcVFo):
 return[UylkJmTOgKHNvMwptSIsnhDxCALErPWcVGd for UylkJmTOgKHNvMwptSIsnhDxCALErPWcVGd in UylkJmTOgKHNvMwptSIsnhDxCALErPWcVFG if UylkJmTOgKHNvMwptSIsnhDxCALErPWcVGd.task_end_time<=UylkJmTOgKHNvMwptSIsnhDxCALErPWcVFX]
def UylkJmTOgKHNvMwptSIsnhDxCALErPWcVGa(UylkJmTOgKHNvMwptSIsnhDxCALErPWcVFz,UylkJmTOgKHNvMwptSIsnhDxCALErPWcVFY):
 UylkJmTOgKHNvMwptSIsnhDxCALErPWcVFj=0
 for UylkJmTOgKHNvMwptSIsnhDxCALErPWcVFq in UylkJmTOgKHNvMwptSIsnhDxCALErPWcVFb(UylkJmTOgKHNvMwptSIsnhDxCALErPWcVFz.no_machines):
  UylkJmTOgKHNvMwptSIsnhDxCALErPWcVFX=0
  for UylkJmTOgKHNvMwptSIsnhDxCALErPWcVFR in UylkJmTOgKHNvMwptSIsnhDxCALErPWcVFY[UylkJmTOgKHNvMwptSIsnhDxCALErPWcVFq]:
   UylkJmTOgKHNvMwptSIsnhDxCALErPWcVFX+=UylkJmTOgKHNvMwptSIsnhDxCALErPWcVXF(UylkJmTOgKHNvMwptSIsnhDxCALErPWcVFz.tasks[UylkJmTOgKHNvMwptSIsnhDxCALErPWcVFR-1].ready-UylkJmTOgKHNvMwptSIsnhDxCALErPWcVFX,0)
   UylkJmTOgKHNvMwptSIsnhDxCALErPWcVFX+=UylkJmTOgKHNvMwptSIsnhDxCALErPWcVFz.machine_speeds[UylkJmTOgKHNvMwptSIsnhDxCALErPWcVFq]*UylkJmTOgKHNvMwptSIsnhDxCALErPWcVFz.tasks[UylkJmTOgKHNvMwptSIsnhDxCALErPWcVFR-1].duration
   UylkJmTOgKHNvMwptSIsnhDxCALErPWcVFj+=UylkJmTOgKHNvMwptSIsnhDxCALErPWcVFX-UylkJmTOgKHNvMwptSIsnhDxCALErPWcVFz.tasks[UylkJmTOgKHNvMwptSIsnhDxCALErPWcVFR-1].ready
 UylkJmTOgKHNvMwptSIsnhDxCALErPWcVFj=UylkJmTOgKHNvMwptSIsnhDxCALErPWcVFj/UylkJmTOgKHNvMwptSIsnhDxCALErPWcVFz.no_tasks
 return Solution(UylkJmTOgKHNvMwptSIsnhDxCALErPWcVFj,Schedule(UylkJmTOgKHNvMwptSIsnhDxCALErPWcVFz.no_tasks,UylkJmTOgKHNvMwptSIsnhDxCALErPWcVFz.no_machines,UylkJmTOgKHNvMwptSIsnhDxCALErPWcVFY))
# Created by pyminifier (https://github.com/liftoff/pyminifier)
