from itertools import takewhile
YbzLvCxiNWDETMfywulqgkOrd=float
YbzLvCxiNWDETMfywulqgkOrc=int
YbzLvCxiNWDETMfywulqgkOrS=min
YbzLvCxiNWDETMfywulqgkOra=len
YbzLvCxiNWDETMfywulqgkOrs=max
YbzLvCxiNWDETMfywulqgkOrH=range
YbzLvCxiNWDETMfywulqgkOrp=enumerate
YbzLvCxiNWDETMfywulqgkOre=list
from typing import NamedTuple
from numpy import average
from p2.src.algorithm_api import Algorithm
from p2.src.data_api import Instance,Solution,Schedule,Task
YbzLvCxiNWDETMfywulqgkOJc=1
YbzLvCxiNWDETMfywulqgkOJS=0
YbzLvCxiNWDETMfywulqgkOJa=3
YbzLvCxiNWDETMfywulqgkOJs=1.5
YbzLvCxiNWDETMfywulqgkOJH=0
class MachineState(NamedTuple):
 YbzLvCxiNWDETMfywulqgkOJp:YbzLvCxiNWDETMfywulqgkOrd
 YbzLvCxiNWDETMfywulqgkOJP:YbzLvCxiNWDETMfywulqgkOrd
 index:YbzLvCxiNWDETMfywulqgkOrc
def YbzLvCxiNWDETMfywulqgkOJr(YbzLvCxiNWDETMfywulqgkOJV):
 return YbzLvCxiNWDETMfywulqgkOJV.speed
def YbzLvCxiNWDETMfywulqgkOJt(YbzLvCxiNWDETMfywulqgkOrm):
 return YbzLvCxiNWDETMfywulqgkOrm[YbzLvCxiNWDETMfywulqgkOJc].duration
def YbzLvCxiNWDETMfywulqgkOJm(YbzLvCxiNWDETMfywulqgkOrm:Task):
 return YbzLvCxiNWDETMfywulqgkOrm.ready
def YbzLvCxiNWDETMfywulqgkOJR(YbzLvCxiNWDETMfywulqgkOJe,YbzLvCxiNWDETMfywulqgkOJG,YbzLvCxiNWDETMfywulqgkOJK,YbzLvCxiNWDETMfywulqgkOJI,YbzLvCxiNWDETMfywulqgkOJQ,enumerated,YbzLvCxiNWDETMfywulqgkOJB):
 YbzLvCxiNWDETMfywulqgkOJe.sort(key=YbzLvCxiNWDETMfywulqgkOJr)
 YbzLvCxiNWDETMfywulqgkOJG.sort(key=YbzLvCxiNWDETMfywulqgkOJt)
 YbzLvCxiNWDETMfywulqgkOJo=YbzLvCxiNWDETMfywulqgkOrS(YbzLvCxiNWDETMfywulqgkOJI,key=lambda m:m.speed)
 YbzLvCxiNWDETMfywulqgkOJA=YbzLvCxiNWDETMfywulqgkOrS(YbzLvCxiNWDETMfywulqgkOJe,key=lambda m:m.speed)
 for YbzLvCxiNWDETMfywulqgkOJV in YbzLvCxiNWDETMfywulqgkOJe:
  if YbzLvCxiNWDETMfywulqgkOra(YbzLvCxiNWDETMfywulqgkOJG)>0:
   if YbzLvCxiNWDETMfywulqgkOJo.task_end_time>YbzLvCxiNWDETMfywulqgkOJB and YbzLvCxiNWDETMfywulqgkOJo.task_end_time<YbzLvCxiNWDETMfywulqgkOJB+YbzLvCxiNWDETMfywulqgkOJa and YbzLvCxiNWDETMfywulqgkOJA.speed>YbzLvCxiNWDETMfywulqgkOJs and YbzLvCxiNWDETMfywulqgkOrs(YbzLvCxiNWDETMfywulqgkOJG,key=lambda t:t[YbzLvCxiNWDETMfywulqgkOJc].duration)[YbzLvCxiNWDETMfywulqgkOJc].duration>1.1*YbzLvCxiNWDETMfywulqgkOJH and YbzLvCxiNWDETMfywulqgkOJA.speed*YbzLvCxiNWDETMfywulqgkOJG[0][YbzLvCxiNWDETMfywulqgkOJc].duration-YbzLvCxiNWDETMfywulqgkOJG[0][YbzLvCxiNWDETMfywulqgkOJc].ready>YbzLvCxiNWDETMfywulqgkOJG[0][YbzLvCxiNWDETMfywulqgkOJc].duration+YbzLvCxiNWDETMfywulqgkOJa-YbzLvCxiNWDETMfywulqgkOJG[0][YbzLvCxiNWDETMfywulqgkOJc].ready:
    break
   if YbzLvCxiNWDETMfywulqgkOJV.speed<YbzLvCxiNWDETMfywulqgkOJs:
    YbzLvCxiNWDETMfywulqgkOJn=YbzLvCxiNWDETMfywulqgkOJG.pop()
   else:
    YbzLvCxiNWDETMfywulqgkOJn=YbzLvCxiNWDETMfywulqgkOJG.pop(0)
   YbzLvCxiNWDETMfywulqgkOJP=YbzLvCxiNWDETMfywulqgkOJB+YbzLvCxiNWDETMfywulqgkOJn[YbzLvCxiNWDETMfywulqgkOJc].duration*YbzLvCxiNWDETMfywulqgkOJV.speed
   YbzLvCxiNWDETMfywulqgkOJK.append(YbzLvCxiNWDETMfywulqgkOJn[0])
   YbzLvCxiNWDETMfywulqgkOJI[YbzLvCxiNWDETMfywulqgkOJV.index]=YbzLvCxiNWDETMfywulqgkOJI[YbzLvCxiNWDETMfywulqgkOJV.index]._replace(task_end_time=YbzLvCxiNWDETMfywulqgkOJP)
   YbzLvCxiNWDETMfywulqgkOJQ[YbzLvCxiNWDETMfywulqgkOJV.index].append(YbzLvCxiNWDETMfywulqgkOJn[0])
   enumerated.remove(YbzLvCxiNWDETMfywulqgkOJn)
class Algorithm136705(Algorithm):
 def YbzLvCxiNWDETMfywulqgkOJF(self,YbzLvCxiNWDETMfywulqgkOrh:Instance)->Solution:
  global YbzLvCxiNWDETMfywulqgkOJH
  YbzLvCxiNWDETMfywulqgkOJB:YbzLvCxiNWDETMfywulqgkOrd=0
  YbzLvCxiNWDETMfywulqgkOJK=[]
  YbzLvCxiNWDETMfywulqgkOJQ=[[]for _ in YbzLvCxiNWDETMfywulqgkOrH(YbzLvCxiNWDETMfywulqgkOrh.no_machines)]
  YbzLvCxiNWDETMfywulqgkOJI=[MachineState(YbzLvCxiNWDETMfywulqgkOJp,0,i)for i,YbzLvCxiNWDETMfywulqgkOJp in YbzLvCxiNWDETMfywulqgkOrp(YbzLvCxiNWDETMfywulqgkOrh.machine_speeds)]
  YbzLvCxiNWDETMfywulqgkOJH=average([YbzLvCxiNWDETMfywulqgkOrm.duration for YbzLvCxiNWDETMfywulqgkOrm in YbzLvCxiNWDETMfywulqgkOrh.tasks])
  YbzLvCxiNWDETMfywulqgkOJj=YbzLvCxiNWDETMfywulqgkOrh.tasks
  YbzLvCxiNWDETMfywulqgkOJj.sort(key=YbzLvCxiNWDETMfywulqgkOJm)
  YbzLvCxiNWDETMfywulqgkOrJ=[[i,val]for i,val in YbzLvCxiNWDETMfywulqgkOrp(YbzLvCxiNWDETMfywulqgkOJj,start=1)]
  while YbzLvCxiNWDETMfywulqgkOra(YbzLvCxiNWDETMfywulqgkOJK)<YbzLvCxiNWDETMfywulqgkOrh.no_tasks:
   YbzLvCxiNWDETMfywulqgkOJe=YbzLvCxiNWDETMfywulqgkOJh(YbzLvCxiNWDETMfywulqgkOJI,YbzLvCxiNWDETMfywulqgkOJB)
   YbzLvCxiNWDETMfywulqgkOJG=YbzLvCxiNWDETMfywulqgkOJX(YbzLvCxiNWDETMfywulqgkOrJ,YbzLvCxiNWDETMfywulqgkOJB)
   if YbzLvCxiNWDETMfywulqgkOra(YbzLvCxiNWDETMfywulqgkOJe)>0 and YbzLvCxiNWDETMfywulqgkOra(YbzLvCxiNWDETMfywulqgkOJG)>0:
    YbzLvCxiNWDETMfywulqgkOJR(YbzLvCxiNWDETMfywulqgkOJe,YbzLvCxiNWDETMfywulqgkOJG,YbzLvCxiNWDETMfywulqgkOJK,YbzLvCxiNWDETMfywulqgkOJI,YbzLvCxiNWDETMfywulqgkOJQ,YbzLvCxiNWDETMfywulqgkOrJ,YbzLvCxiNWDETMfywulqgkOJB)
    YbzLvCxiNWDETMfywulqgkOJB+=1
   elif YbzLvCxiNWDETMfywulqgkOra(YbzLvCxiNWDETMfywulqgkOJe)==0:
    YbzLvCxiNWDETMfywulqgkOJB=YbzLvCxiNWDETMfywulqgkOrs(YbzLvCxiNWDETMfywulqgkOrS(YbzLvCxiNWDETMfywulqgkOJI,key=lambda YbzLvCxiNWDETMfywulqgkOJV:YbzLvCxiNWDETMfywulqgkOJV.task_end_time).task_end_time,YbzLvCxiNWDETMfywulqgkOJB)
   elif YbzLvCxiNWDETMfywulqgkOra(YbzLvCxiNWDETMfywulqgkOJG)==0:
    YbzLvCxiNWDETMfywulqgkOJB=YbzLvCxiNWDETMfywulqgkOrS(YbzLvCxiNWDETMfywulqgkOrJ,key=lambda YbzLvCxiNWDETMfywulqgkOrm:YbzLvCxiNWDETMfywulqgkOrm[YbzLvCxiNWDETMfywulqgkOJc].ready)[YbzLvCxiNWDETMfywulqgkOJc].ready
   else:
    YbzLvCxiNWDETMfywulqgkOJB+=1
  return YbzLvCxiNWDETMfywulqgkOJd(YbzLvCxiNWDETMfywulqgkOrh,YbzLvCxiNWDETMfywulqgkOJQ)
def YbzLvCxiNWDETMfywulqgkOJX(YbzLvCxiNWDETMfywulqgkOJj,YbzLvCxiNWDETMfywulqgkOJB:YbzLvCxiNWDETMfywulqgkOrd):
 return YbzLvCxiNWDETMfywulqgkOre(YbzLvCxiNWDETMfywulqgkOrt(lambda YbzLvCxiNWDETMfywulqgkOrm:YbzLvCxiNWDETMfywulqgkOrm[YbzLvCxiNWDETMfywulqgkOJc].ready<=YbzLvCxiNWDETMfywulqgkOJB,YbzLvCxiNWDETMfywulqgkOJj))
def YbzLvCxiNWDETMfywulqgkOJh(YbzLvCxiNWDETMfywulqgkOJI,YbzLvCxiNWDETMfywulqgkOJB:YbzLvCxiNWDETMfywulqgkOrd):
 return[YbzLvCxiNWDETMfywulqgkOJV for YbzLvCxiNWDETMfywulqgkOJV in YbzLvCxiNWDETMfywulqgkOJI if YbzLvCxiNWDETMfywulqgkOJV.task_end_time<=YbzLvCxiNWDETMfywulqgkOJB]
def YbzLvCxiNWDETMfywulqgkOJd(YbzLvCxiNWDETMfywulqgkOrh,YbzLvCxiNWDETMfywulqgkOJQ):
 YbzLvCxiNWDETMfywulqgkOrR=0
 for YbzLvCxiNWDETMfywulqgkOrF in YbzLvCxiNWDETMfywulqgkOrH(YbzLvCxiNWDETMfywulqgkOrh.no_machines):
  YbzLvCxiNWDETMfywulqgkOJB=0
  for YbzLvCxiNWDETMfywulqgkOrX in YbzLvCxiNWDETMfywulqgkOJQ[YbzLvCxiNWDETMfywulqgkOrF]:
   YbzLvCxiNWDETMfywulqgkOJB+=YbzLvCxiNWDETMfywulqgkOrs(YbzLvCxiNWDETMfywulqgkOrh.tasks[YbzLvCxiNWDETMfywulqgkOrX-1].ready-YbzLvCxiNWDETMfywulqgkOJB,0)
   YbzLvCxiNWDETMfywulqgkOJB+=YbzLvCxiNWDETMfywulqgkOrh.machine_speeds[YbzLvCxiNWDETMfywulqgkOrF]*YbzLvCxiNWDETMfywulqgkOrh.tasks[YbzLvCxiNWDETMfywulqgkOrX-1].duration
   YbzLvCxiNWDETMfywulqgkOrR+=YbzLvCxiNWDETMfywulqgkOJB-YbzLvCxiNWDETMfywulqgkOrh.tasks[YbzLvCxiNWDETMfywulqgkOrX-1].ready
 YbzLvCxiNWDETMfywulqgkOrR=YbzLvCxiNWDETMfywulqgkOrR/YbzLvCxiNWDETMfywulqgkOrh.no_tasks
 return Solution(YbzLvCxiNWDETMfywulqgkOrR,Schedule(YbzLvCxiNWDETMfywulqgkOrh.no_tasks,YbzLvCxiNWDETMfywulqgkOrh.no_machines,YbzLvCxiNWDETMfywulqgkOJQ))
